services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
        VITE_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - backend
    ports:
      - "80:80"