# render.yaml
services:
  # ---------- FastAPI backend ----------
  - type: web
    name: backend
    env: docker
    plan: free
    rootDir: ./backend
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - fromGroup: boostfit-secrets
  # ---------- Nginx (Vite build) frontend ----------
  - type: web
    name: frontend
    env: docker
    plan: free
    rootDir: ./frontend
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - fromGroup: boostfit-secrets
