# motivation-app/render.yaml

services:
  # The Python/FastAPI backend service
  - type: web
    name: backend
    env: docker
    rootDir: ./backend
    healthCheck:
      path: /health
      port: 8000
    # Link to the secret group you will create in the Render dashboard
    envVarGroups:
      - name: boostfit-secrets

  # The React/Nginx frontend service
  - type: web
    name: frontend
    env: docker
    rootDir: ./frontend
    # These build arguments are passed to your frontend Dockerfile
    dockerBuildArgs:
      VITE_API_URL: /api
      VITE_SUPABASE_URL: $VITE_SUPABASE_URL
      VITE_SUPABASE_ANON_KEY: $VITE_SUPABASE_ANON_KEY
    # Link to the same secret group to get the values for the build args
    envVarGroups:
      - name: boostfit-secrets