# motivation-app/render.yaml

services:
  # The Python/FastAPI backend service
  - type: web
    name: backend
    env: docker
    rootDir: ./backend
    healthCheck:
      path: /health
      port: 8000
    envVarGroups:
      - name: boostfit-secrets # Link to your secrets

  # The React/Nginx frontend service
  - type: web
    name: frontend
    env: docker
    rootDir: ./frontend
    envVars:
      - key: VITE_API_URL # This is passed to the Docker build
        value: /api
    envVarGroups:
      - name: boostfit-secrets # Also links to secrets for build args